FROM snakepacker/python:all AS builder

RUN python3.7 -m venv /usr/share/python3/app

ADD requirements*.txt /mnt/
RUN /usr/share/python3/app/bin/pip install -U pip setuptools

RUN apt-get update && \
    apt-get install python-dev

ADD dist/ /tmp/app/
RUN /usr/share/python3/app/bin/pip install /tmp/app/*

RUN /usr/share/python3/app/bin/pip install -Ur /mnt/requirements.dev.txt && \
    /usr/share/python3/app/bin/pip check

WORKDIR /mnt/
#ADD calendar_fu /mnt/app/
ADD tests/ /mnt/tests/
#ADD tests/conftest.py /mnt/conftest.py
#RUN ln -snf /usr/share/python3/app/bin/ /usr/bin/
RUN ln -snf /usr/share/python3/app/bin/fu_calendar /usr/bin/
ENV PATH="/usr/share/python3/app/bin:${PATH}"
#ENV PYTHONPATH="/mnt/app"