"""init

Revision ID: a74e424d2975
Revises: 
Create Date: 2019-12-09 20:53:34.377910

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a74e424d2975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_update', sa.DateTime(), nullable=False),
                    sa.Column('last_use', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('calendars')
    # ### end Alembic commands ###
